#!/usr/bin/env bash
# Bash script that displays text with condtion
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/my_script.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
while true
do
	echo "To infinity and beyond"
	sleep 2
done
