#!/usr/bin/env bash
# displays numbers from 1 to 100
# FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3
# Buzz when the number is a multiple of 5

for (( i=1; i<=100; i++ ))
do
	if (($i%3 = 0))
	then
		echo "Fizz"
	elif (($i%5 = 0))
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
