#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# Only display username, user id, Home directory path for the user
while IFS= read -r LINE
do
	echo "$LINE" | cut -d ":" -f 1,3,6
done < /etc/passwd
