#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd
# using the while loop + IFS.
while IFS= read -r LINE;
do
	USERNAME=$(echo "$LINE" | cut -d ":" -f 1)
	GROUP_ID=$(echo "$LINE" | cut -d ":" -f 4)
	HOME_DIRECTORY=$(echo "$LINE" | cut -d ":" -f 6)
	COMMAND=$(echo "$LINE" | cut -d ":" -f 7)
	USER_ID=$(echo "$LINE" | cut -d ":" -f 3)
	PASSWORD="$(echo "$LINE" | cut -d ":" -f 2)"

	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USERNAME"
done < /etc/passwd
