#!/usr/bin/env bash
# Bash script that displays the visitor IP along with 
# the HTTP status code from the Apache log file.
while IFS= read -r LINE;
do
	awk '{print $1 " "$9}'
done < apache-access.log
