#!/usr/bin/env bash
# This script is displaying 1 to 20
# And some numbers based on superstitious beliefs

i=1

while [ $i -le 20 ]
do
	if [ $i = 4 ]
	then
		echo "bad luck from China"
	elif [ $i = 9 ]
	then
		echo "bad luck from Japan"
	elif [ $i = 17 ]
	then
		echo "bad luck from Italy"
	else
		echo "$i"
	fi

	(( i++ ))
done
