#!/usr/bin/env bash
# Bash script that displays
# The content of the current directory In a list format
# Where only the part of the name after the first dash is displayed
LIST="$(ls)"
for ITEM in $LIST
do
	echo "$ITEM" | cut -d "-" -f 2
done
