#!/usr/bin/env bash
# Displays the contents of current Directory in a list format
# Where only the part of the name after the first dash is displayed

for line in *
do
	echo "$line" | cut -d "-" -f2
done
