#!/usr/bin/env bash
# Bash script that gives you information about the school file
# if the file exists: school file exists
# if the file does not exist: school file does not exist
FILE="school"
#checking if the file exist
if [ -e "$FILE" ]
then
	echo "$FILE file exists"
	#if the file is not empty
	if [ -s "$FILE" ]
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
	#if the file is regular
	if [ -f "$FILE" ]
	then
		echo "$FILE is a regular file"
	fi
else
	#if the file is empty
	echo "$FILE file does not exist"
fi
