#!/usr/bin/env bash
# Bash script that gives you information about the school file
# if the file exists: school file exists
# if the file does not exist: school file does not exist
FILE="school"
#checking if the file exist
if [ -e "$FILE" ];
then
	echo "school file exists"
	#if the file is not empty
	if [ -s "$FILE"];
	then
		echo "school file is not empty"
		#if the file is regular
		if [ -f "$FILE" ];
		then
			echo "school is a regular file"
		fi
	else
		echo "school file is empty"
	fi
else
	#if the file is empty
	echo "school file does not exist"
fi
