#!/usr/bin/env bash
# Script that runs Nginx as Nginx user
pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo sed -i "s/#user www-data;/nginx user;/" /etc/nginx/nginx.conf
